In [16]:
import numpy as np
from sympy import *

In [ ]:
# -Padalinkite intervalą nuo -1.3 iki 2.5 tolygiai į 64 dalis.
def first():
  return np.linspace(-1.3, 2.5, num=64)

first()

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

In [ ]:
# -Sugeneruokite masyvą dydžio 3n ir užpildykite jį cikliniu šablonu [1, 2, 3].
def second(n):
  return np.tile([1,2,3], n)

second(6)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
# -Sukurkite masyvą iš pirmųjų 10 nelyginių sveikųjų skaičių.
def third():
  return np.arange(1,20,2)

third()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
# -Sukurkite masyvą dydžio 10 x 10 iš nulių ir "įrėminkite" jį vienetais.
def forth():
  base = np.zeros(12*12).reshape(12,12)
  base[:, 11] = 1
  base[11, :] = 1
  base[:, 0] = 1
  base[0, :] = 1
  return base

forth()

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# -Sukurkite masyvą dydžio 8 x 8, kur 1 ir 0 išdėlioti šachmatine tvarka (panaudokite slicing+striding metodą).
def fifth():
  line = np.ones(8)
  line[::2] = np.zeros(int(8/2))
  rev_line = line[::-1]
  two_lines = np.hstack((line, rev_line))
  board_arr = np.tile(two_lines, int(8/2))
  return board_arr.reshape(8, 8)
  
fifth()

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
# -Sukurkite masyvą dydžio n×n , kurio (i,j)-oji pozicija lygi i+j
def sixth(n, i, j):
  base_arr = np.full((n, n), None)
  base_arr[i,j] = i*j
  return base_arr

sixth(10, 4, 5)

array([[None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, 20, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None]],
      dtype=object)

In [ ]:
# -Sukurkite atsitiktinį masyvą dydžio 3×5 naudodami np.random.rand(3, 5) funkciją ir suskaičiuokite: sumą, eilučių sumą, stulpelių sumą.
def seventh():
  base = np.random.rand(3, 5)
  print('Sum: ' + str(base.sum()))
  print('row sums: ' + str(base.sum(axis=1)))
  print('col sums: ' + str(base.sum(axis=0)))
seventh()

Sum: 7.011501162306144
row sums: [2.15638224 2.19467582 2.66044311]
col sums: [1.70115095 1.05459805 1.70477555 1.76784618 0.78313043]


In [ ]:
# -Sukurkite atsitiktinį masyvą dydžio 5×5 naudodami np.random.rand(5, 5). Surūšiuokite eilutes pagal antrąjį stulpelį. Tam pamėginkite apjungti masyvo slicing + argsort + indexing metodus.
def eigth():
  base = np.random.rand(5, 5)
  return base[base[:, 1].argsort()]
eigth()

array([[0.75408145, 0.2184752 , 0.80089401, 0.10068179, 0.16664913],
       [0.97269305, 0.32266546, 0.60800897, 0.74580676, 0.97031954],
       [0.40272771, 0.47674205, 0.31282171, 0.71804099, 0.9258283 ],
       [0.33343055, 0.52171098, 0.52507748, 0.38922213, 0.82919017],
       [0.00789307, 0.96881923, 0.85112483, 0.29714637, 0.64828701]])

In [13]:
# -Atvirkštinę matricą
def ninth(matrix):
  return np.linalg.inv(matrix)

a = np.array([[1,2],[3,4]])
ninth(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [15]:
# -Apskaičiuokite matricos tikrines reikšmes ir tikrinį vektorių
def tenth(matrix):
  return np.linalg.eig(matrix)

tenth(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [17]:
# -Pasirinktos funkcijos išvestinę
def eleventh(math_function):
  return diff(math_function)

x = symbols('x')
y = x**2 + 1
eleventh(y)

2*x

In [18]:
# -Pasirinktos funkcijos apibrėžtinį ir neapibrėžtinį integralus
def twelfth(math_function):
  return integrate(math_function)

twelfth(y)

x**3/3 + x